version: "3"

services:
  start-dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - mongo
      - rabbitmq
    command: rabbitmq:5672

  api:
    build: ../src/Actio.Api
    links:
      - rabbitmq
      - mongo
    ports:
      - "5000:5000"
      - "5001:5001"

  activities-service:
    build: ../src/Actio.Services.Activities
    links:
      - rabbitmq
      - mongo
    ports:
      - "5050:5050"
      - "5051:5051"

  identity-service:
    build: ../src/Actio.Services.Identity
    links:
      - rabbitmq
      - mongo
    ports:
      - "5100:5100"
      - "5101:5101"

  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
